### ISSUE TITLE
Create Card component

### ISSUE THREAD

**Issue by rmariuzzo** [react-spectre/react-spectre#10]
Follow [Spectre.css card component](https://picturepan2.github.io/spectre/components.html#cards).

**Comment by kensuka21** [comment]
I'll be working on this !

**Comment by kensuka21** [comment]
Check the PR when you can. [#35](https://github.com/react-spectre/react-spectre/pull/35)

Regards.

**Comment by rmariuzzo** [comment]
Ty! Added you as a contributor. 😎
