### ISSUE TITLE
Create Navbar component

### ISSUE THREAD

**Issue by rmariuzzo** [react-spectre/react-spectre#3]
Follow [Spectre.css media elements](https://picturepan2.github.io/spectre/layout.html#navbar).

 - [ ] Create `Navbar` component.
 - [ ] Create `Section` (alias `Navbar.Section`) component with `center` prop.

**Comment by 0aps** [comment]
Hellou, 
   I'll work this one out.

Regards
A

**Comment by AlburIvan** [comment]
________________________________

**Comment by 0aps** [comment]
Hello, 
     Just created PR #26 for current issue. Please verify when possible. 

Regards
A
