### ISSUE TITLE
Create Accordion component

### ISSUE THREAD

**Issue by rmariuzzo** [react-spectre/react-spectre#4]
Follow [Spectre.css accordions component](https://picturepan2.github.io/spectre/components.html#accordions).

 - [ ] Create an `Accordion` component with `children` prop.
 - [ ] Create an `Accordion.Body` component with `header` and `children` prop.

**Comment by 0aps** [comment]
Helou, 
  I'll work this one.

Regards,
A

**Comment by 0aps** [comment]
Hello, 
  I worked the current issue on PR #27 . 

Regards, 
Ángel
