### ISSUE TITLE
Create Autocomplete component

### ISSUE THREAD

**Issue by rmariuzzo** [react-spectre/react-spectre#5]
Follow [Spectre.css autocomplete component](https://picturepan2.github.io/spectre/components.html#autocomplete).

**Comment by 0aps** [comment]
Hello, 

   I'll work this one.

Regards, 
Ángel

**Comment by 0aps** [comment]
Hello, 
I have implemented the current issue in PR #29 . Please review when possible.

Regards
Ángel
