### ISSUE TITLE
Create Avatar component

### ISSUE THREAD

**Issue by rmariuzzo** [react-spectre/react-spectre#6]
Follow [Spectre.css avatars component](https://picturepan2.github.io/spectre/components.html#avatars).

**Comment by 0aps** [comment]
Hello, 
  I'll work on this one. 

Regards, 
Ángel

**Comment by rmariuzzo** [comment]
You are on 🔥  !

**Comment by 0aps** [comment]
Hello,
 I have implemented current issue on PR #30 . Please check it out when possible.

Regards, 
Ángel
